server:
  port: 8888
  servlet:
    context-path: /
spring:
  application:
    name: jeesd-sys-service
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  datasource:
    url: jdbc:mysql://192.168.1.209:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 25000
      login-timeout: 5
      max-lifetime: 30000
      read-only: false
      validation-timeout: 3000
      maximum-pool-size: 15
      minimum-idle: 10
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

security:
  oauth2:
    client:
      client-id: jeesd
      client-secret: e10adc3949ba59abbe56e057f20f883e
    resource:
      id: jeesd-sys-service
      token-info-uri: http://localhost:8444/auth/oauth/check_token
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.jeesd.sys.domain,com.jeesd.sys.dto
  global-config:
    db-config:
      id-type: AUTO
      field-strategy: NOT_NULL
      db-type: mysql
    banner: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://jeesd:jeesd@localhost:8088/eureka/

logging:
  file: jeesd-sys-service
  level:
    org.mybatis: info
    org.springframework.web: error
    com.jeesd.sys: debug
